permalink: /:year/:month/:day/:title
highlighter: rouge
markdown: kramdown
excerpt_separator: <!--more-->
paginate: 5

exclude: [
  README.md,
  localserver,
  build,
  Gemfile,
  Gemfile.lock
]

collections:
  tags:
    output: true
    permalink: /blog/tags/:name/
  projects:
    output: true
    premalink: /projects/:name/

sass:
  sass_dir: _scss

defaults:
  -
    scope:
      path: ""
      type: tags
    values:
      layout: tag_page
  -
    scope:
      path: ""
      type: projects
    values:
      layout: project_page


# Comments
disqus: "arubertoson"


# Setup
name: Marcus Albertsson
title: Marcus Albertsson
tagline: Personal Blog
description: This is a blog about my development adventures and other interests.
url: https://arubertoson.github.io
baseurl: /
